---
name: "Test"
on:
  pull_request:
  push:
    branches:
      - "qa/**"
      - "stable/**"
      - "dev/drop-py27"
      - "dev/upgrade-django"
jobs:
  test:
    name: "Test ${{ matrix.tox_section }} on ${{ matrix.python_version_in.docker }}"
    runs-on: "ubuntu-18.04"
    strategy:
      fail-fast: false
      matrix:
        tox_section:
          - "storage-service"
          - "migrations"
        python_version_in:
          - docker: "3.6"
            tox: "py36"
          - docker: "3.7"
            tox: "py37"
          - docker: "3.8"
            tox: "py38"
          - docker: "3.9"
            tox: "py39"
        include:
          - tox_section: "storage-service"
            coverage: true
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v2"
      - name: "Set up Python ${{ matrix.python_version_in.docker }}"
        uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python_version_in.docker }}"
      - name: "Install OS packages"
        run: |
          sudo apt-get --quiet update
          sudo apt-get install --quiet --yes build-essential \
            libmysqlclient-dev libsasl2-dev libldap2-dev libssl-dev \
            p7zip-full unar
      - name: "Create directories needed by test_duracloud.py"
        run: |
          sudo mkdir -p /var/archivematica/storage_service
          sudo chown -R $USER /var/archivematica/storage_service
      - name: "Get pip cache dir"
        id: "pip-cache"
        run: |
          echo "::set-output name=dir::$(pip cache dir)"
      - name: "Cache pip packages"
        uses: "actions/cache@v2"
        with:
          path: "${{ steps.pip-cache.outputs.dir }}"
          key: "${{ runner.os }}-pip-${{ hashFiles('**/requirements/test.txt') }}"
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: "Install tox"
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: "Run tox"
        if: "! matrix.coverage"
        env:
          TOXENV: ${{ matrix.python_version_in.tox }}-${{ matrix.tox_section }}
          PYTEST_ADDOPTS: -vv
        run: |
          tox
      - name: "Run tox with coverage"
        if: "matrix.coverage"
        env:
          TOXENV: ${{ matrix.python_version_in.tox }}-${{ matrix.tox_section }}
          PYTEST_ADDOPTS: -vv --cov storage_service --cov-config=.coveragerc --cov-report xml:coverage.xml
        run: |
          tox
      - name: "Upload coverage report"
        if: matrix.coverage && github.repository == 'artefactual/archivematica-storage-service'
        uses: "codecov/codecov-action@v1"
        with:
          files: ./coverage.xml
          fail_ci_if_error: true
          verbose: true
          name: ${{ matrix.tox_section }}-${{ matrix.python_version_in.docker }}
          flags: ${{ matrix.python_version_in.tox }}
  integration:
    name: "Integration on ${{ matrix.python_version }}"
    runs-on: "ubuntu-18.04"
    strategy:
      fail-fast: false
      matrix:
        python_version:
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v2"
      - name: "Run tests"
        run: |
          ./run.sh
        shell: "bash"
        working-directory: "integration"
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
          PYTEST_ADDOPTS: -vv
          PYTHON_VERSION: ${{ matrix.python_version }}
  linting:
    name: "Lint"
    runs-on: "ubuntu-18.04"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v2"
      - name: "Set up Python 3.6"
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.6"
      - name: "Install tox"
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: "Run tox"
        run: |
          tox -e linting
